import type { Component } from 'vue'
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  Apple,
  ArrowDown,
  ArrowLeftRight,
  ArrowUp,
  BaggageClaim,
  Banknote,
  BarChart3,
  Bell,
  Bike,
  BookOpen,
  Briefcase,
  Building,
  Building2,
  Bus,
  Cake,
  Calculator,
  Calendar,
  Camera,
  Car,
  ChartColumn,
  Check,
  CheckCircle,
  ChevronLeft,
  ChevronRight,
  CircleDot,
  Clock,
  Cloud,
  Coffee,
  Copy,
  CreditCard,
  DollarSign,
  Download,
  Droplets,
  Edit3,
  Eye,
  EyeOff,
  ExternalLink,
  FileText,
  Film,
  Flame,
  Frown,
  Gamepad2,
  Gift,
  GraduationCap,
  Hash,
  Heart,
  HeartPulse,
  Headphones,
  HelpCircle,
  Home,
  Image,
  Info,
  Laptop,
  Link2,
  Loader2,
  Lock,
  Mail,
  MapPin,
  Minus,
  MinusCircle,
  Moon,
  MoreHorizontal,
  Music,
  Navigation,
  Package,
  Paperclip,
  Percent,
  Pencil,
  Pen,
  PieChart,
  Pill,
  Pizza,
  Plane,
  Plus,
  PlusCircle,
  Printer,
  Receipt,
  RefreshCw,
  Save,
  Search,
  Settings,
  Share2,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Smile,
  Smartphone,
  Star,
  Stethoscope,
  Sun,
  Target,
  Train,
  Trash2,
  TrendingDown,
  TrendingUp,
  Tv,
  Umbrella,
  Unlock,
  Upload,
  User,
  Users,
  Utensils,
  Video,
  Volume2,
  Wallet,
  X,
  XCircle,
  Zap,
} from '@lucide/vue'

export const iconRegistry = {
  Activity,
  AlertCircle,
  AlertTriangle,
  Apple,
  ArrowDown,
  ArrowLeftRight,
  ArrowUp,
  BaggageClaim,
  Banknote,
  BarChart3,
  Bell,
  Bike,
  BookOpen,
  Briefcase,
  Building,
  Building2,
  Bus,
  Cake,
  Calculator,
  Calendar,
  Camera,
  Car,
  ChartColumn,
  Check,
  CheckCircle,
  ChevronLeft,
  ChevronRight,
  CircleDot,
  Clock,
  Cloud,
  Coffee,
  Copy,
  CreditCard,
  DollarSign,
  Download,
  Droplets,
  Edit3,
  Eye,
  EyeOff,
  ExternalLink,
  FileText,
  Film,
  Flame,
  Frown,
  Gamepad2,
  Gift,
  GraduationCap,
  Hash,
  Heart,
  HeartPulse,
  Headphones,
  HelpCircle,
  Home,
  Image,
  Info,
  Laptop,
  Link2,
  Loader2,
  Lock,
  Mail,
  MapPin,
  Minus,
  MinusCircle,
  Moon,
  MoreHorizontal,
  Music,
  Navigation,
  Package,
  Paperclip,
  Percent,
  Pencil,
  Pen,
  PieChart,
  Pill,
  Pizza,
  Plane,
  Plus,
  PlusCircle,
  Printer,
  Receipt,
  RefreshCw,
  Save,
  Search,
  Settings,
  Share2,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Smile,
  Smartphone,
  Star,
  Stethoscope,
  Sun,
  Target,
  Train,
  Trash2,
  TrendingDown,
  TrendingUp,
  Tv,
  Umbrella,
  Unlock,
  Upload,
  User,
  Users,
  Utensils,
  Video,
  Volume2,
  Wallet,
  X,
  XCircle,
  Zap,
} as const satisfies Readonly<Record<string, Component>>

export type IconName = keyof typeof iconRegistry

export const pickerIconNames = [
  'Wallet', 'Banknote', 'CreditCard', 'Building2', 'DollarSign', 'Percent',
  'TrendingUp', 'TrendingDown', 'BarChart3', 'PieChart', 'Activity', 'Target',
  'Utensils', 'Coffee', 'Pizza', 'Apple', 'Cake',
  'Car', 'Train', 'Bus', 'Bike', 'Plane', 'Navigation',
  'Home', 'ShoppingCart', 'BaggageClaim', 'Gift', 'Package',
  'Smartphone', 'Laptop', 'Tv', 'Gamepad2', 'Music', 'Headphones', 'Camera', 'Film',
  'BookOpen', 'GraduationCap', 'Pen', 'FileText',
  'HeartPulse', 'Pill', 'Stethoscope', 'Activity',
  'Briefcase', 'Users', 'User', 'Building',
  'MoreHorizontal', 'Settings', 'HelpCircle', 'Info', 'AlertCircle',
  'CheckCircle', 'XCircle', 'PlusCircle', 'MinusCircle',
  'Sun', 'Moon', 'Cloud', 'Umbrella', 'Zap', 'Droplets', 'Flame',
  'Star', 'Heart', 'Smile', 'Frown',
  'Search', 'Plus', 'Minus', 'Check', 'X', 'ArrowUp', 'ArrowDown',
  'RefreshCw', 'Download', 'Upload', 'Share2', 'ExternalLink',
  'MapPin', 'Calendar', 'Clock', 'Bell', 'Mail',
  'Trash2', 'Edit3', 'Copy', 'Save', 'Printer',
  'Lock', 'Unlock', 'Eye', 'EyeOff', 'Shield',
  'Link2', 'Paperclip', 'Image', 'Video', 'Volume2',
] as const satisfies readonly IconName[]

// 將 PascalCase、camelCase 與 kebab-case 圖示名稱統一成 registry key。
export function normalizeIconName(name: string): string {
  return name.trim()
    .replace(/-(\w)/g, (_, character: string) => character.toUpperCase())
    .replace(/^(\w)/, (_, character: string) => character.toUpperCase())
}

// 解析受支援圖示，並以中性 HelpCircle 處理空白或未知的 persisted value。
export function resolveIcon(name: string): Component {
  const normalizedName = normalizeIconName(name) as IconName
  return iconRegistry[normalizedName] ?? iconRegistry.HelpCircle
}
